-- Base schema for core tables and lookup data

create extension if not exists "pgcrypto";

create table if not exists public.domains (
  id bigint generated by default as identity primary key,
  name text not null unique
);

create table if not exists public.problem_statements (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  domain_id bigint not null references public.domains(id)
);

create unique index if not exists problem_statements_title_unique
  on public.problem_statements(title);

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  email text not null unique,
  phone text,
  role text not null,
  university_name text not null,
  event_hub_id text,
  created_at timestamptz not null default now(),
  onboarding_complete boolean not null default false
);

create table if not exists public.teams (
  id uuid primary key default gen_random_uuid(),
  team_name text not null,
  team_code text not null unique,
  problem_statement_id bigint references public.problem_statements(id),
  domain_id bigint references public.domains(id),
  payment_link text,
  payment_verified boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  leader_user_id uuid references auth.users(id),
  lead_email text
);

create table if not exists public.team_members (
  team_id uuid not null references public.teams(id) on delete cascade,
  user_id uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  primary key (team_id, user_id)
);

create or replace function public.handle_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.generate_unique_team_code()
returns text
language plpgsql
set search_path = public
as $$
declare
  candidate text;
begin
  loop
    candidate := upper(substr(encode(gen_random_bytes(4), 'hex'), 1, 6));
    exit when not exists (
      select 1 from public.teams where team_code = candidate
    );
  end loop;
  return candidate;
end;
$$;

create or replace function public.set_team_code()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.team_code is null or new.team_code = '' then
    new.team_code := public.generate_unique_team_code();
  else
    new.team_code := upper(new.team_code);
  end if;
  return new;
end;
$$;

create or replace function public.check_team_size_limit()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  member_count integer;
begin
  select count(*) into member_count
  from public.team_members
  where team_id = new.team_id;

  if member_count >= 4 then
    raise exception 'Team is already full';
  end if;

  return new;
end;
$$;

drop trigger if exists set_team_code on public.teams;
create trigger set_team_code
  before insert on public.teams
  for each row
  execute function public.set_team_code();

drop trigger if exists on_team_update on public.teams;
create trigger on_team_update
  before update on public.teams
  for each row
  execute function public.handle_updated_at();

drop trigger if exists enforce_team_size on public.team_members;
create trigger enforce_team_size
  before insert on public.team_members
  for each row
  execute function public.check_team_size_limit();

alter table public.domains enable row level security;
alter table public.problem_statements enable row level security;

drop policy if exists domains_select_public on public.domains;
create policy domains_select_public
  on public.domains
  for select
  using (true);

drop policy if exists problem_statements_select_public on public.problem_statements;
create policy problem_statements_select_public
  on public.problem_statements
  for select
  using (true);

insert into public.domains (name)
values
  ('AI/ML'),
  ('Cybersecurity'),
  ('Healthcare'),
  ('Fintech'),
  ('IoT & Robotics')
on conflict (name) do nothing;

insert into public.problem_statements (title, description, domain_id)
select
  'AI-Powered Sustainability Platform',
  'Design and develop a platform that leverages AI to track, analyze, and reduce carbon footprints in real time.',
  d.id
from public.domains d
where d.name = 'AI/ML'
  and not exists (
    select 1 from public.problem_statements ps
    where ps.title = 'AI-Powered Sustainability Platform'
  );

insert into public.problem_statements (title, description, domain_id)
select
  'Threat Intelligence Automation',
  'Build a system that correlates security alerts and automates response playbooks for common attack vectors.',
  d.id
from public.domains d
where d.name = 'Cybersecurity'
  and not exists (
    select 1 from public.problem_statements ps
    where ps.title = 'Threat Intelligence Automation'
  );

insert into public.problem_statements (title, description, domain_id)
select
  'Predictive Care Navigator',
  'Create an intelligent assistant that triages patient data to recommend proactive care journeys.',
  d.id
from public.domains d
where d.name = 'Healthcare'
  and not exists (
    select 1 from public.problem_statements ps
    where ps.title = 'Predictive Care Navigator'
  );

insert into public.problem_statements (title, description, domain_id)
select
  'Inclusive Credit Scoring',
  'Design a model that responsibly scores underserved users using alternative data signals.',
  d.id
from public.domains d
where d.name = 'Fintech'
  and not exists (
    select 1 from public.problem_statements ps
    where ps.title = 'Inclusive Credit Scoring'
  );

insert into public.problem_statements (title, description, domain_id)
select
  'Autonomous Field Robotics',
  'Develop a control system that orchestrates cooperative robots for inspection and maintenance.',
  d.id
from public.domains d
where d.name = 'IoT & Robotics'
  and not exists (
    select 1 from public.problem_statements ps
    where ps.title = 'Autonomous Field Robotics'
  );
